### ISSUE TITLE
_myTrait_.reactLiteral not working

### ISSUE THREAD

**Issue by LukasOchmann** [terotests/ASTWalker#1]
i use espree to parse an JSXString in to AST, in the String is an ternary operator like:
`aVariable.indexOf('test String') > -1 ? doSomething : doSomethingElse`.
The problem is -1 is not a String and your Method `reactLiteral` trys to use trim on the value wich runs into an error.

**Comment by terotests** [comment]
Thanks for notifying - first Issue, btw 👍  - I'll check this today, should be trivial to fix or if you want to create a PR that would be great too.

**Comment by LukasOchmann** [comment]
ok i have a solution. i will create a PR

**Comment by terotests** [comment]
I checked the source and minified the original (just to be sure it is the same) - at some point have to split the codebase to separate files, current version was created using my own build-tool.
