### ISSUE TITLE
Could you list all options possible? 

### ISSUE THREAD

**Issue by LukasOchmann** [terotests/ASTWalker#3]
i found 4:

- defaultNamespace:String
- forceNamespace:boolean
- toES5:boolean
- noOutput:???

and tell what they are doing?
Thank you

**Comment by terotests** [comment]
I'll update docs, when I find a bit time, maybe 1-2 days or so.

**Comment by terotests** [comment]
I added docs ++ added the changes from the other PR you made to change only the `0.95` version - let's work on that 0.95 for a while if you find something else -> just create a new branch on that.
